#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use lazybot\Addic7edCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\DependencyInjection\ContainerBuilder;

$command = new Addic7edCommand();

$application = new Application('LazyBot', '0.0.1');
$application->add($command);
$application->run();
