#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use lazybot\Addic7edCommand;
use lazybot\LazyBotMonitoringCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\DependencyInjection\ContainerBuilder;

$application = new Application('LazyBot', '0.0.1');
$application->add(new Addic7edCommand());
$application->add(new LazyBotMonitoringCommand());
$application->run();
